# RuboCop Default Config: https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

AllCops:
  NewCops: disable

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
