name: ci

on:
  push:
    paths-ignore:
      - '**.md'
      - '.rubocop.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.rubocop.yml'

jobs:
  build-and-test:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15]
        ruby-version: ['2.5', '2.6', '2.7']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    
    - name: Install protoc
      run: |
        PROTOC_VER="3.17.3"
        PROTOC_PKG=""
        if [ "$RUNNER_OS" == "Linux" ]; then
          PROTOC_PKG="protoc-$PROTOC_VER-linux-x86_64.zip"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          PROTOC_PKG="protoc-$PROTOC_VER-osx-x86_64.zip"
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
        echo "Installing $PROTOC_PKG"
        mkdir protoc && cd protoc
        wget https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VER/$PROTOC_PKG
        unzip $PROTOC_PKG
        chmod +x ./bin/protoc
        sudo mv ./bin/protoc /usr/local/bin/protoc
        sudo mv ./include/* /usr/local/include/
        rm -rf protoc
        protoc --version
        echo "$PROTOC_PKG installed successfully"

    - name: Build and install
      run: |
        gem build *.gemspec
        sudo gem install *.gem
        proto-convert -h
        echo "proto-convert installed successfully"

    - name: Test
      run: ./test/run_tests.sh
