name: ci

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '.rubocop.yml']
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths-ignore: ['**.md', '.rubocop.yml']

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby-version: ['2.6', '2.7', '3.5']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout [${{ github.repository }}]
      uses: actions/checkout@v3

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install protoc
      uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ruby-version == '2.6' && '3.x' || '' }}
        include-pre-releases: true

    - name: Build and install
      shell: bash
      env:
        RUBY_VERSION: ${{ matrix.ruby-version }}
      run: |
        if [[ $RUBY_VERSION == '2.6' ]]; then
          gem install google-protobuf -v 3.12.2
        else
          gem install google-protobuf
        fi
        gem build *.gemspec
        gem install *.gem
        proto-convert --help

    - name: Run tests [${{ matrix.os }}]
      shell: bash
      run: cd test && ./run_tests.sh
