name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.rubocop.yml'
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'
      - '.rubocop.yml'

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, macos-latest]
        ruby-version: ['2.6']
        # ruby-version: ['2.6', '2.7']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install protoc
      uses: arduino/setup-protoc@v1

    - name: Build and install
      run: |
        gem build *.gemspec
        gem install *.gem
        proto-convert -h

    - name: Run tests
      run: cd test && ./run_tests.sh
