name: ci

on:
  push:
    paths-ignore:
      - '**.md'
      - '.rubocop.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.rubocop.yml'

jobs:
  build-and-test:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby-version: ['2.6', '2.7']

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Install protoc
      uses: arduino/setup-protoc@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and install
      run: |
        gem build *.gemspec
        gem install *.gem
        proto-convert -h

    - name: Test
      run: ./test/run_tests.sh
