name: ci

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '.rubocop.yml']
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths-ignore: ['**.md', '.rubocop.yml']

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby-version: ['2.6', '2.7']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout [${{ github.repository }}]
      uses: actions/checkout@v3

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install protoc
      uses: arduino/setup-protoc@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and install
      run: |
        gem build *.gemspec
        gem install *.gem
        proto-convert -h

    - name: Run tests [${{ matrix.os }}]
      if: ${{ runner.os != 'Windows' }}
      run: cd test && ./run_tests.sh
